//
// Workspace.swift
//

import ProjectDescription

let workspace = Workspace(
  name: "TCATuistBoilerplate",
  projects: [
    "./TCATuistBoilerplate",
    "./Features/*",
  ],
  generationOptions: .options(
    autogeneratedWorkspaceSchemes: .disabled,
    lastXcodeUpgradeCheck: Version(16, 1, 0)
  )
)
